// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqjYZ4_NXX9VsTySNcvDiUSbJJppTiLLk',
    appId: '1:465643215953:web:ccf8371f435f1ddc2dac70',
    messagingSenderId: '465643215953',
    projectId: 'emlakflutter-662b0',
    authDomain: 'emlakflutter-662b0.firebaseapp.com',
    storageBucket: 'emlakflutter-662b0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSs6UntI7nDQLhI3ppL584nsDN75mXFh4',
    appId: '1:465643215953:android:f44680f85a451e3e2dac70',
    messagingSenderId: '465643215953',
    projectId: 'emlakflutter-662b0',
    storageBucket: 'emlakflutter-662b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZpngdlxnolllzYzc8pjkRKa4m7sFS_Zs',
    appId: '1:465643215953:ios:1f84f18c1d075e592dac70',
    messagingSenderId: '465643215953',
    projectId: 'emlakflutter-662b0',
    storageBucket: 'emlakflutter-662b0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZpngdlxnolllzYzc8pjkRKa4m7sFS_Zs',
    appId: '1:465643215953:ios:1f84f18c1d075e592dac70',
    messagingSenderId: '465643215953',
    projectId: 'emlakflutter-662b0',
    storageBucket: 'emlakflutter-662b0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqjYZ4_NXX9VsTySNcvDiUSbJJppTiLLk',
    appId: '1:465643215953:web:3e8315c39ae6a01f2dac70',
    messagingSenderId: '465643215953',
    projectId: 'emlakflutter-662b0',
    authDomain: 'emlakflutter-662b0.firebaseapp.com',
    storageBucket: 'emlakflutter-662b0.firebasestorage.app',
  );
}
